/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "communicate.h"


void
communicate_prog_1(char *host)
{
	CLIENT *clnt;
	NodeList  *result_1;
	char *find_1_filename;
	int  *result_2;
	char *download_1_filename;
	int  *result_3;
	FileList  *result_4;
	void *vp1;
	void *vp2;

#ifndef	DEBUG
	clnt = clnt_create (host, COMMUNICATE_PROG, COMMUNICATE_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = find_1(find_1_filename, clnt);
	if (result_1 == (NodeList *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = download_1(download_1_filename, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = getload_1(vp1, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = updatelist_1(vp2, clnt);
	if (result_4 == (FileList *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}



int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	communicate_prog_1 (host);
exit (0);
}
