/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "communicate.h"

//global nodelist 
// global int load
// global char[120] this_peer_dir
// global filelist
// global char[120] server_type

// void scan(char *dir){
	//fileList 
	// for each file in dir
// }

// void download_thread(void *arg){
	// get the file name
	// get the peer ip and port
	// get the file from the peer
	// update the file list
	// call scan
//}

// node* peer_select(NodeList *list){
	// select a peer from the list based on load and latency
	// return the peer
// }

// void read_config(){
	//hardcoded file name/path
// }


NodeList *
find_1_svc(char *filename,  struct svc_req *rqstp)
{
	static NodeList  result;

	/*
	 * insert server code here
	 */
	//if server_type == trackingserver

	// only called by peers to trackingserver
	// return list of peers that have the file
	// for loop updatelist across all peers
	// 		update the global node list
	// return list of peers that have the file

	return &result;
}

int *
download_1_svc(char *filename,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	//after download, call scan

	return &result;
}

int *
getload_1_svc(struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	// lock the load variable
	// read it 
	// unlock it
	// return it


	return &result;
}

FileList *
updatelist_1_svc(struct svc_req *rqstp)
{
	static FileList  result;

	/*
	 * insert server code here
	 */
	//scan directory for files

	return &result;
}
