/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "communicate.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static NodeList *
_find_1 (char * *argp, struct svc_req *rqstp)
{
	return (find_1_svc(*argp, rqstp));
}

static int *
_download_1 (char * *argp, struct svc_req *rqstp)
{
	return (download_1_svc(*argp, rqstp));
}

static int *
_getload_1 (getload_1_argument *argp, struct svc_req *rqstp)
{
	return (getload_1_svc(argp->ip, argp->port, rqstp));
}

static FileList *
_updatelist_1 (updatelist_1_argument *argp, struct svc_req *rqstp)
{
	return (updatelist_1_svc(argp->ip, argp->port, rqstp));
}

static void
communicate_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *find_1_arg;
		char *download_1_arg;
		getload_1_argument getload_1_arg;
		updatelist_1_argument updatelist_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case Find:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_NodeList;
		local = (char *(*)(char *, struct svc_req *)) _find_1;
		break;

	case Download:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _download_1;
		break;

	case GetLoad:
		_xdr_argument = (xdrproc_t) xdr_getload_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _getload_1;
		break;

	case UpdateList:
		_xdr_argument = (xdrproc_t) xdr_updatelist_1_argument;
		_xdr_result = (xdrproc_t) xdr_FileList;
		local = (char *(*)(char *, struct svc_req *)) _updatelist_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	if (argc < 4) {
		printf ("usage: %s server_ip server_port dir\n", argv[0]);
		exit (1);
	}

	char *server_ip = argv[1];

	char *server_port_str = argv[2];
	int server_port_int = atoi(server_port_str);

	char *dir = argv[3];


	initialize(server_ip, server_port_str, dir);
	register SVCXPRT *transp;

	pmap_unset (COMMUNICATE_PROG, COMMUNICATE_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, COMMUNICATE_PROG, COMMUNICATE_VERSION, communicate_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (COMMUNICATE_PROG, COMMUNICATE_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, COMMUNICATE_PROG, COMMUNICATE_VERSION, communicate_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (COMMUNICATE_PROG, COMMUNICATE_VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
