/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "communicate.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

NodeList *
find_1(char *filename,  CLIENT *clnt)
{
	static NodeList clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, Find,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &filename,
		(xdrproc_t) xdr_NodeList, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
download_1(char *filename,  CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, Download,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &filename,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
getload_1(char *ip, int port,  CLIENT *clnt)
{
	getload_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ip = ip;
	arg.port = port;
	if (clnt_call (clnt, GetLoad, (xdrproc_t) xdr_getload_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

FileList *
updatelist_1(char *ip, int port,  CLIENT *clnt)
{
	updatelist_1_argument arg;
	static FileList clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ip = ip;
	arg.port = port;
	if (clnt_call (clnt, UpdateList, (xdrproc_t) xdr_updatelist_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_FileList, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
